#!/usr/bin/env python3

TYPE_LUA = 'Lua'

TYPE_BIN_BATTLE_PARAM = 'BattleParam'
TYPE_BIN_MENU_PARAM = 'MenuParam'
TYPE_BIN_TEXT_PARAM = 'TextParam'
TYPE_BIN_PARAM = 'Param'
TYPE_BIN_TEXT = 'Text'
TYPE_BIN_LIST = 'List'
TYPE_BIN_PAGE = 'Page'

TYPES_BIN = [TYPE_BIN_BATTLE_PARAM, TYPE_BIN_MENU_PARAM, TYPE_BIN_TEXT_PARAM, TYPE_BIN_PARAM, TYPE_BIN_TEXT, TYPE_BIN_LIST, TYPE_BIN_PAGE]
