#!/usr/bin/env python3

TYPE_LUA = 'Lua'

TYPE_BIN_CHAR_BATTLE_PARAM = 'CharBattleParam'
TYPE_BIN_CHAR_MENU_PARAM = 'CharMenuParam'
TYPE_BIN_CAD_TEXT_PARAM = 'CadTextParam'
TYPE_BIN_CAD_PARAM = 'CadParam'
TYPE_BIN_MAGIC_TEXT = 'MagicText'
TYPE_BIN_TUTORIAL_LIST = 'TutorialList'
TYPE_BIN_TUNING_LIST = 'TuningList'

TYPES_BIN = [TYPE_BIN_CHAR_BATTLE_PARAM, TYPE_BIN_CHAR_MENU_PARAM, TYPE_BIN_CAD_TEXT_PARAM, TYPE_BIN_CAD_PARAM, TYPE_BIN_MAGIC_TEXT, TYPE_BIN_TUTORIAL_LIST, TYPE_BIN_TUNING_LIST]

LENGTH_BIN_CAD_PARAM_CHUNK = 0x164
LENGTH_BIN_CHAR_MENU_PARAM_CHUNK = 0x144
